### ISSUE TITLE
There have some build error .

### ISSUE THREAD

**Issue by sunlifeng** [acropolium/SharpGs#1]
Error   1   Default parameter specifiers are not permitted SharpGs\Internal\SharpGsClient.cs    36  82  SharpGs

**Comment by ioleksiy** [comment]
There is no build error. You need to install latest framework .Net 4.0. And run it on Visual Studio 2010.

**Comment by sunlifeng** [comment]
OK,I know . I'm using Visual c# 2008 Express
 The default parameters was add by C# 4.0 .Why not write a more compatible program ?
I will try Visual Studio 2010 when I get a  powerful computer .:)

**Comment by ioleksiy** [comment]
That was a choice of modern technologies. You can fork and remake it if something is not good for you.

**Comment by sunlifeng** [comment]
OK OK I will try
